// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type CommentDto struct {
	PostID int    `json:"PostId"`
	ID     string `json:"Id"`
	Name   string `json:"Name"`
	Email  string `json:"Email"`
	Body   string `json:"Body"`
}

type InputGetComment struct {
	ID     int `json:"Id"`
	PostID int `json:"PostId"`
}
